version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - srvnetwork

  app:
    build:
      context: node
    container_name: app
    entrypoint: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "50s", "--", "node", "index.js"]
    networks:
      - srvnetwork
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
       - db

  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks: 
      - srvnetwork
    ports: 
      - "8080:80"
    depends_on: 
       - app

networks:
  srvnetwork:
    name: srvnetwork
    driver: bridge